// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package form

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO forms (title, description, last_edit)
VALUES ($1, $2, $3) 
RETURNING id, title, description, last_edit, created_at, updated_at
`

type CreateParams struct {
	Title       string
	Description pgtype.Text
	LastEdit    pgtype.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Form, error) {
	row := q.db.QueryRow(ctx, create, arg.Title, arg.Description, arg.LastEdit)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LastEdit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM forms WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, title, description, last_edit, created_at, updated_at FROM forms WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (Form, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LastEdit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const list = `-- name: List :many
SELECT id, title, description, last_edit, created_at, updated_at FROM forms ORDER BY updated_at DESC
`

func (q *Queries) List(ctx context.Context) ([]Form, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.LastEdit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE forms
SET title = $2, description = $3, last_edit = $4, updated_at = now()
WHERE id = $1
RETURNING id, title, description, last_edit, created_at, updated_at
`

type UpdateParams struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	LastEdit    pgtype.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Form, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.LastEdit,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LastEdit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
