// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"NYCU-SDC/core-system-backend/internal/form/workflow"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function for the type MockQuerier
func (_mock *MockQuerier) Activate(ctx context.Context, arg workflow.ActivateParams) (workflow.ActivateRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 workflow.ActivateRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.ActivateParams) (workflow.ActivateRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.ActivateParams) workflow.ActivateRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(workflow.ActivateRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, workflow.ActivateParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockQuerier_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - arg workflow.ActivateParams
func (_e *MockQuerier_Expecter) Activate(ctx interface{}, arg interface{}) *MockQuerier_Activate_Call {
	return &MockQuerier_Activate_Call{Call: _e.mock.On("Activate", ctx, arg)}
}

func (_c *MockQuerier_Activate_Call) Run(run func(ctx context.Context, arg workflow.ActivateParams)) *MockQuerier_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 workflow.ActivateParams
		if args[1] != nil {
			arg1 = args[1].(workflow.ActivateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_Activate_Call) Return(activateRow workflow.ActivateRow, err error) *MockQuerier_Activate_Call {
	_c.Call.Return(activateRow, err)
	return _c
}

func (_c *MockQuerier_Activate_Call) RunAndReturn(run func(ctx context.Context, arg workflow.ActivateParams) (workflow.ActivateRow, error)) *MockQuerier_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNode provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateNode(ctx context.Context, arg workflow.CreateNodeParams) (workflow.CreateNodeRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateNode")
	}

	var r0 workflow.CreateNodeRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.CreateNodeParams) (workflow.CreateNodeRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.CreateNodeParams) workflow.CreateNodeRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(workflow.CreateNodeRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, workflow.CreateNodeParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNode'
type MockQuerier_CreateNode_Call struct {
	*mock.Call
}

// CreateNode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg workflow.CreateNodeParams
func (_e *MockQuerier_Expecter) CreateNode(ctx interface{}, arg interface{}) *MockQuerier_CreateNode_Call {
	return &MockQuerier_CreateNode_Call{Call: _e.mock.On("CreateNode", ctx, arg)}
}

func (_c *MockQuerier_CreateNode_Call) Run(run func(ctx context.Context, arg workflow.CreateNodeParams)) *MockQuerier_CreateNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 workflow.CreateNodeParams
		if args[1] != nil {
			arg1 = args[1].(workflow.CreateNodeParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateNode_Call) Return(createNodeRow workflow.CreateNodeRow, err error) *MockQuerier_CreateNode_Call {
	_c.Call.Return(createNodeRow, err)
	return _c
}

func (_c *MockQuerier_CreateNode_Call) RunAndReturn(run func(ctx context.Context, arg workflow.CreateNodeParams) (workflow.CreateNodeRow, error)) *MockQuerier_CreateNode_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNode provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteNode(ctx context.Context, arg workflow.DeleteNodeParams) ([]byte, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNode")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.DeleteNodeParams) ([]byte, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.DeleteNodeParams) []byte); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, workflow.DeleteNodeParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_DeleteNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNode'
type MockQuerier_DeleteNode_Call struct {
	*mock.Call
}

// DeleteNode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg workflow.DeleteNodeParams
func (_e *MockQuerier_Expecter) DeleteNode(ctx interface{}, arg interface{}) *MockQuerier_DeleteNode_Call {
	return &MockQuerier_DeleteNode_Call{Call: _e.mock.On("DeleteNode", ctx, arg)}
}

func (_c *MockQuerier_DeleteNode_Call) Run(run func(ctx context.Context, arg workflow.DeleteNodeParams)) *MockQuerier_DeleteNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 workflow.DeleteNodeParams
		if args[1] != nil {
			arg1 = args[1].(workflow.DeleteNodeParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteNode_Call) Return(bytes []byte, err error) *MockQuerier_DeleteNode_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockQuerier_DeleteNode_Call) RunAndReturn(run func(ctx context.Context, arg workflow.DeleteNodeParams) ([]byte, error)) *MockQuerier_DeleteNode_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockQuerier
func (_mock *MockQuerier) Get(ctx context.Context, formID uuid.UUID) (workflow.GetRow, error) {
	ret := _mock.Called(ctx, formID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 workflow.GetRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (workflow.GetRow, error)); ok {
		return returnFunc(ctx, formID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) workflow.GetRow); ok {
		r0 = returnFunc(ctx, formID)
	} else {
		r0 = ret.Get(0).(workflow.GetRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockQuerier_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - formID uuid.UUID
func (_e *MockQuerier_Expecter) Get(ctx interface{}, formID interface{}) *MockQuerier_Get_Call {
	return &MockQuerier_Get_Call{Call: _e.mock.On("Get", ctx, formID)}
}

func (_c *MockQuerier_Get_Call) Run(run func(ctx context.Context, formID uuid.UUID)) *MockQuerier_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_Get_Call) Return(getRow workflow.GetRow, err error) *MockQuerier_Get_Call {
	_c.Call.Return(getRow, err)
	return _c
}

func (_c *MockQuerier_Get_Call) RunAndReturn(run func(ctx context.Context, formID uuid.UUID) (workflow.GetRow, error)) *MockQuerier_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockQuerier
func (_mock *MockQuerier) Update(ctx context.Context, arg workflow.UpdateParams) (workflow.UpdateRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 workflow.UpdateRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.UpdateParams) (workflow.UpdateRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.UpdateParams) workflow.UpdateRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(workflow.UpdateRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, workflow.UpdateParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockQuerier_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - arg workflow.UpdateParams
func (_e *MockQuerier_Expecter) Update(ctx interface{}, arg interface{}) *MockQuerier_Update_Call {
	return &MockQuerier_Update_Call{Call: _e.mock.On("Update", ctx, arg)}
}

func (_c *MockQuerier_Update_Call) Run(run func(ctx context.Context, arg workflow.UpdateParams)) *MockQuerier_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 workflow.UpdateParams
		if args[1] != nil {
			arg1 = args[1].(workflow.UpdateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_Update_Call) Return(updateRow workflow.UpdateRow, err error) *MockQuerier_Update_Call {
	_c.Call.Return(updateRow, err)
	return _c
}

func (_c *MockQuerier_Update_Call) RunAndReturn(run func(ctx context.Context, arg workflow.UpdateParams) (workflow.UpdateRow, error)) *MockQuerier_Update_Call {
	_c.Call.Return(run)
	return _c
}
