// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"NYCU-SDC/core-system-backend/internal/form/workflow"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function for the type MockValidator
func (_mock *MockValidator) Activate(ctx context.Context, formID uuid.UUID, workflow1 []byte, questionStore workflow.QuestionStore) error {
	ret := _mock.Called(ctx, formID, workflow1, questionStore)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, workflow.QuestionStore) error); ok {
		r0 = returnFunc(ctx, formID, workflow1, questionStore)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockValidator_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - formID uuid.UUID
//   - workflow1 []byte
//   - questionStore workflow.QuestionStore
func (_e *MockValidator_Expecter) Activate(ctx interface{}, formID interface{}, workflow1 interface{}, questionStore interface{}) *MockValidator_Activate_Call {
	return &MockValidator_Activate_Call{Call: _e.mock.On("Activate", ctx, formID, workflow1, questionStore)}
}

func (_c *MockValidator_Activate_Call) Run(run func(ctx context.Context, formID uuid.UUID, workflow1 []byte, questionStore workflow.QuestionStore)) *MockValidator_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 workflow.QuestionStore
		if args[3] != nil {
			arg3 = args[3].(workflow.QuestionStore)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockValidator_Activate_Call) Return(err error) *MockValidator_Activate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_Activate_Call) RunAndReturn(run func(ctx context.Context, formID uuid.UUID, workflow1 []byte, questionStore workflow.QuestionStore) error) *MockValidator_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockValidator
func (_mock *MockValidator) Validate(ctx context.Context, formID uuid.UUID, workflow1 []byte, questionStore workflow.QuestionStore) error {
	ret := _mock.Called(ctx, formID, workflow1, questionStore)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, workflow.QuestionStore) error); ok {
		r0 = returnFunc(ctx, formID, workflow1, questionStore)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - formID uuid.UUID
//   - workflow1 []byte
//   - questionStore workflow.QuestionStore
func (_e *MockValidator_Expecter) Validate(ctx interface{}, formID interface{}, workflow1 interface{}, questionStore interface{}) *MockValidator_Validate_Call {
	return &MockValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, formID, workflow1, questionStore)}
}

func (_c *MockValidator_Validate_Call) Run(run func(ctx context.Context, formID uuid.UUID, workflow1 []byte, questionStore workflow.QuestionStore)) *MockValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 workflow.QuestionStore
		if args[3] != nil {
			arg3 = args[3].(workflow.QuestionStore)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockValidator_Validate_Call) Return(err error) *MockValidator_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, formID uuid.UUID, workflow1 []byte, questionStore workflow.QuestionStore) error) *MockValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateNodeIDsUnchanged provides a mock function for the type MockValidator
func (_mock *MockValidator) ValidateNodeIDsUnchanged(ctx context.Context, currentWorkflow []byte, newWorkflow []byte) error {
	ret := _mock.Called(ctx, currentWorkflow, newWorkflow)

	if len(ret) == 0 {
		panic("no return value specified for ValidateNodeIDsUnchanged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte) error); ok {
		r0 = returnFunc(ctx, currentWorkflow, newWorkflow)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_ValidateNodeIDsUnchanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateNodeIDsUnchanged'
type MockValidator_ValidateNodeIDsUnchanged_Call struct {
	*mock.Call
}

// ValidateNodeIDsUnchanged is a helper method to define mock.On call
//   - ctx context.Context
//   - currentWorkflow []byte
//   - newWorkflow []byte
func (_e *MockValidator_Expecter) ValidateNodeIDsUnchanged(ctx interface{}, currentWorkflow interface{}, newWorkflow interface{}) *MockValidator_ValidateNodeIDsUnchanged_Call {
	return &MockValidator_ValidateNodeIDsUnchanged_Call{Call: _e.mock.On("ValidateNodeIDsUnchanged", ctx, currentWorkflow, newWorkflow)}
}

func (_c *MockValidator_ValidateNodeIDsUnchanged_Call) Run(run func(ctx context.Context, currentWorkflow []byte, newWorkflow []byte)) *MockValidator_ValidateNodeIDsUnchanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockValidator_ValidateNodeIDsUnchanged_Call) Return(err error) *MockValidator_ValidateNodeIDsUnchanged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_ValidateNodeIDsUnchanged_Call) RunAndReturn(run func(ctx context.Context, currentWorkflow []byte, newWorkflow []byte) error) *MockValidator_ValidateNodeIDsUnchanged_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUpdateNodeIDs provides a mock function for the type MockValidator
func (_mock *MockValidator) ValidateUpdateNodeIDs(ctx context.Context, currentWorkflow []byte, newWorkflow []byte) error {
	ret := _mock.Called(ctx, currentWorkflow, newWorkflow)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUpdateNodeIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte) error); ok {
		r0 = returnFunc(ctx, currentWorkflow, newWorkflow)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_ValidateUpdateNodeIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUpdateNodeIDs'
type MockValidator_ValidateUpdateNodeIDs_Call struct {
	*mock.Call
}

// ValidateUpdateNodeIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - currentWorkflow []byte
//   - newWorkflow []byte
func (_e *MockValidator_Expecter) ValidateUpdateNodeIDs(ctx interface{}, currentWorkflow interface{}, newWorkflow interface{}) *MockValidator_ValidateUpdateNodeIDs_Call {
	return &MockValidator_ValidateUpdateNodeIDs_Call{Call: _e.mock.On("ValidateUpdateNodeIDs", ctx, currentWorkflow, newWorkflow)}
}

func (_c *MockValidator_ValidateUpdateNodeIDs_Call) Run(run func(ctx context.Context, currentWorkflow []byte, newWorkflow []byte)) *MockValidator_ValidateUpdateNodeIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockValidator_ValidateUpdateNodeIDs_Call) Return(err error) *MockValidator_ValidateUpdateNodeIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_ValidateUpdateNodeIDs_Call) RunAndReturn(run func(ctx context.Context, currentWorkflow []byte, newWorkflow []byte) error) *MockValidator_ValidateUpdateNodeIDs_Call {
	_c.Call.Return(run)
	return _c
}
