// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function for the type MockValidator
func (_mock *MockValidator) Activate(workflow []byte) error {
	ret := _mock.Called(workflow)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(workflow)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockValidator_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - workflow []byte
func (_e *MockValidator_Expecter) Activate(workflow interface{}) *MockValidator_Activate_Call {
	return &MockValidator_Activate_Call{Call: _e.mock.On("Activate", workflow)}
}

func (_c *MockValidator_Activate_Call) Run(run func(workflow []byte)) *MockValidator_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValidator_Activate_Call) Return(err error) *MockValidator_Activate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_Activate_Call) RunAndReturn(run func(workflow []byte) error) *MockValidator_Activate_Call {
	_c.Call.Return(run)
	return _c
}
