// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"NYCU-SDC/core-system-backend/internal/form/question"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockQuerier
func (_mock *MockQuerier) Create(ctx context.Context, params question.CreateParams) (question.Question, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, question.CreateParams) (question.Question, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, question.CreateParams) question.Question); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(question.Question)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, question.CreateParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockQuerier_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params question.CreateParams
func (_e *MockQuerier_Expecter) Create(ctx interface{}, params interface{}) *MockQuerier_Create_Call {
	return &MockQuerier_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockQuerier_Create_Call) Run(run func(ctx context.Context, params question.CreateParams)) *MockQuerier_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 question.CreateParams
		if args[1] != nil {
			arg1 = args[1].(question.CreateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_Create_Call) Return(question1 question.Question, err error) *MockQuerier_Create_Call {
	_c.Call.Return(question1, err)
	return _c
}

func (_c *MockQuerier_Create_Call) RunAndReturn(run func(ctx context.Context, params question.CreateParams) (question.Question, error)) *MockQuerier_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockQuerier
func (_mock *MockQuerier) Delete(ctx context.Context, params question.DeleteParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, question.DeleteParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockQuerier_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - params question.DeleteParams
func (_e *MockQuerier_Expecter) Delete(ctx interface{}, params interface{}) *MockQuerier_Delete_Call {
	return &MockQuerier_Delete_Call{Call: _e.mock.On("Delete", ctx, params)}
}

func (_c *MockQuerier_Delete_Call) Run(run func(ctx context.Context, params question.DeleteParams)) *MockQuerier_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 question.DeleteParams
		if args[1] != nil {
			arg1 = args[1].(question.DeleteParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_Delete_Call) Return(err error) *MockQuerier_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_Delete_Call) RunAndReturn(run func(ctx context.Context, params question.DeleteParams) error) *MockQuerier_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetByID(ctx context.Context, id uuid.UUID) (question.Question, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (question.Question, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) question.Question); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(question.Question)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockQuerier_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetByID(ctx interface{}, id interface{}) *MockQuerier_GetByID_Call {
	return &MockQuerier_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockQuerier_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetByID_Call) Return(question1 question.Question, err error) *MockQuerier_GetByID_Call {
	_c.Call.Return(question1, err)
	return _c
}

func (_c *MockQuerier_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (question.Question, error)) *MockQuerier_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByFormID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListByFormID(ctx context.Context, formID uuid.UUID) ([]question.Question, error) {
	ret := _mock.Called(ctx, formID)

	if len(ret) == 0 {
		panic("no return value specified for ListByFormID")
	}

	var r0 []question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]question.Question, error)); ok {
		return returnFunc(ctx, formID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []question.Question); ok {
		r0 = returnFunc(ctx, formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListByFormID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByFormID'
type MockQuerier_ListByFormID_Call struct {
	*mock.Call
}

// ListByFormID is a helper method to define mock.On call
//   - ctx context.Context
//   - formID uuid.UUID
func (_e *MockQuerier_Expecter) ListByFormID(ctx interface{}, formID interface{}) *MockQuerier_ListByFormID_Call {
	return &MockQuerier_ListByFormID_Call{Call: _e.mock.On("ListByFormID", ctx, formID)}
}

func (_c *MockQuerier_ListByFormID_Call) Run(run func(ctx context.Context, formID uuid.UUID)) *MockQuerier_ListByFormID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListByFormID_Call) Return(questions []question.Question, err error) *MockQuerier_ListByFormID_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *MockQuerier_ListByFormID_Call) RunAndReturn(run func(ctx context.Context, formID uuid.UUID) ([]question.Question, error)) *MockQuerier_ListByFormID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockQuerier
func (_mock *MockQuerier) Update(ctx context.Context, params question.UpdateParams) (question.Question, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, question.UpdateParams) (question.Question, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, question.UpdateParams) question.Question); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(question.Question)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, question.UpdateParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockQuerier_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - params question.UpdateParams
func (_e *MockQuerier_Expecter) Update(ctx interface{}, params interface{}) *MockQuerier_Update_Call {
	return &MockQuerier_Update_Call{Call: _e.mock.On("Update", ctx, params)}
}

func (_c *MockQuerier_Update_Call) Run(run func(ctx context.Context, params question.UpdateParams)) *MockQuerier_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 question.UpdateParams
		if args[1] != nil {
			arg1 = args[1].(question.UpdateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_Update_Call) Return(question1 question.Question, err error) *MockQuerier_Update_Call {
	_c.Call.Return(question1, err)
	return _c
}

func (_c *MockQuerier_Update_Call) RunAndReturn(run func(ctx context.Context, params question.UpdateParams) (question.Question, error)) *MockQuerier_Update_Call {
	_c.Call.Return(run)
	return _c
}
