// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package inbox

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO inbox_message (posted_by, type, content_id)
VALUES ($1, $2, $3)
RETURNING id, posted_by, type, content_id, created_at, updated_at
`

type CreateMessageParams struct {
	PostedBy  uuid.UUID
	Type      ContentType
	ContentID uuid.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.PostedBy, arg.Type, arg.ContentID)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.PostedBy,
		&i.Type,
		&i.ContentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserInboxBulk = `-- name: CreateUserInboxBulk :many
INSERT INTO user_inbox_messages (user_id, message_id)
SELECT unnest($1::uuid[]), $2::uuid
RETURNING id, user_id, message_id, is_read, is_starred, is_archived
`

type CreateUserInboxBulkParams struct {
	Column1 []uuid.UUID
	Column2 uuid.UUID
}

func (q *Queries) CreateUserInboxBulk(ctx context.Context, arg CreateUserInboxBulkParams) ([]UserInboxMessage, error) {
	rows, err := q.db.Query(ctx, createUserInboxBulk, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInboxMessage
	for rows.Next() {
		var i UserInboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.IsRead,
			&i.IsStarred,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT uim.id, user_id, message_id, is_read, is_starred, is_archived, im.id, posted_by, type, content_id, created_at, updated_at
FROM user_inbox_messages uim
JOIN inbox_message im ON uim.message_id = im.id
WHERE uim.id = $1 AND uim.user_id = $2
`

type GetByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetByIDRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	MessageID  uuid.UUID
	IsRead     bool
	IsStarred  bool
	IsArchived bool
	ID_2       uuid.UUID
	PostedBy   uuid.UUID
	Type       ContentType
	ContentID  uuid.UUID
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) GetByID(ctx context.Context, arg GetByIDParams) (GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, arg.ID, arg.UserID)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageID,
		&i.IsRead,
		&i.IsStarred,
		&i.IsArchived,
		&i.ID_2,
		&i.PostedBy,
		&i.Type,
		&i.ContentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const list = `-- name: List :many
SELECT uim.id, user_id, message_id, is_read, is_starred, is_archived, im.id, posted_by, type, content_id, created_at, updated_at
FROM user_inbox_messages uim
JOIN inbox_message im ON uim.message_id = im.id
WHERE uim.user_id = $1
`

type ListRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	MessageID  uuid.UUID
	IsRead     bool
	IsStarred  bool
	IsArchived bool
	ID_2       uuid.UUID
	PostedBy   uuid.UUID
	Type       ContentType
	ContentID  uuid.UUID
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) List(ctx context.Context, userID uuid.UUID) ([]ListRow, error) {
	rows, err := q.db.Query(ctx, list, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRow
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.IsRead,
			&i.IsStarred,
			&i.IsArchived,
			&i.ID_2,
			&i.PostedBy,
			&i.Type,
			&i.ContentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateByID = `-- name: UpdateByID :one
UPDATE user_inbox_messages AS uim
SET is_read = $3, is_starred = $4, is_archived = $5
FROM inbox_message AS im
WHERE uim.message_id = im.id AND uim.id = $1 AND uim.user_id = $2
RETURNING im.id, posted_by, type, content_id, created_at, updated_at, uim.id, user_id, message_id, is_read, is_starred, is_archived
`

type UpdateByIDParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IsRead     bool
	IsStarred  bool
	IsArchived bool
}

type UpdateByIDRow struct {
	ID         uuid.UUID
	PostedBy   uuid.UUID
	Type       ContentType
	ContentID  uuid.UUID
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	ID_2       uuid.UUID
	UserID     uuid.UUID
	MessageID  uuid.UUID
	IsRead     bool
	IsStarred  bool
	IsArchived bool
}

func (q *Queries) UpdateByID(ctx context.Context, arg UpdateByIDParams) (UpdateByIDRow, error) {
	row := q.db.QueryRow(ctx, updateByID,
		arg.ID,
		arg.UserID,
		arg.IsRead,
		arg.IsStarred,
		arg.IsArchived,
	)
	var i UpdateByIDRow
	err := row.Scan(
		&i.ID,
		&i.PostedBy,
		&i.Type,
		&i.ContentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.UserID,
		&i.MessageID,
		&i.IsRead,
		&i.IsStarred,
		&i.IsArchived,
	)
	return i, err
}
