// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package workflow

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const get = `-- name: Get :one
SELECT workflow, id, form_id, last_editor, is_active, created_at, updated_at
FROM workflow_versions
WHERE form_id = $1
ORDER BY updated_at DESC
LIMIT 1
`

type GetRow struct {
	Workflow   []byte
	ID         uuid.UUID
	FormID     uuid.UUID
	LastEditor uuid.UUID
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) Get(ctx context.Context, formID uuid.UUID) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, formID)
	var i GetRow
	err := row.Scan(
		&i.Workflow,
		&i.ID,
		&i.FormID,
		&i.LastEditor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
