// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package question

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Provider   string
	ProviderID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Form struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	LastEditor  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Question struct {
	ID          uuid.UUID
	FormID      uuid.UUID
	Required    bool
	Type        string
	Label       pgtype.Text
	Description pgtype.Text
	Order       int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RefreshToken struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	IsActive       pgtype.Bool
	ExpirationDate pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Name      pgtype.Text
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	Role      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
