// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package question

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
WITH inserted AS (
    INSERT INTO questions (section_id, required, type, title, description, metadata, "order", source_id)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, section_id, required, type, title, description, metadata, "order", source_id, created_at, updated_at
)
SELECT 
    i.id,
    i.section_id,
    i.required,
    i.type,
    i.title,
    i.description,
    i.metadata,
    i."order",
    i.source_id,
    i.created_at,
    i.updated_at,
    s.form_id
FROM inserted i
JOIN sections s ON i.section_id = s.id
`

type CreateParams struct {
	SectionID   uuid.UUID
	Required    bool
	Type        QuestionType
	Title       pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	Order       int32
	SourceID    pgtype.UUID
}

type CreateRow struct {
	ID          uuid.UUID
	SectionID   uuid.UUID
	Required    bool
	Type        QuestionType
	Title       pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	Order       int32
	SourceID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	FormID      uuid.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (CreateRow, error) {
	row := q.db.QueryRow(ctx, create,
		arg.SectionID,
		arg.Required,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Metadata,
		arg.Order,
		arg.SourceID,
	)
	var i CreateRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormID,
	)
	return i, err
}

const deleteAndReorder = `-- name: DeleteAndReorder :exec
WITH deleted_row AS (
    DELETE FROM questions q
    WHERE q.section_id = $1 AND q.id = $2
    RETURNING "order" as old_order, section_id
)
UPDATE questions q
SET "order" = q."order" - 1
FROM deleted_row
WHERE q.section_id = deleted_row.section_id
  AND "order" > deleted_row.old_order
`

type DeleteAndReorderParams struct {
	SectionID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteAndReorder(ctx context.Context, arg DeleteAndReorderParams) error {
	_, err := q.db.Exec(ctx, deleteAndReorder, arg.SectionID, arg.ID)
	return err
}

const getByID = `-- name: GetByID :one
SELECT 
    q.id,
    q.section_id,
    q.required,
    q.type,
    q.title,
    q.description,
    q.metadata,
    q."order",
    q.source_id,
    q.created_at,
    q.updated_at,
    s.form_id
FROM questions q
JOIN sections s ON q.section_id = s.id
WHERE q.id = $1
`

type GetByIDRow struct {
	ID          uuid.UUID
	SectionID   uuid.UUID
	Required    bool
	Type        QuestionType
	Title       pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	Order       int32
	SourceID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	FormID      uuid.UUID
}

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormID,
	)
	return i, err
}

const listByFormID = `-- name: ListByFormID :many
SELECT
    s.id as section_id,
    s.form_id,
    s.title,
    s.progress,
    s.description,
    s.created_at,
    s.updated_at,
    q.id,
    q.required,
    q.type,
    q.title as question_title,
    q.description as question_description,
    q.metadata,
    q."order",
    q.source_id,
    q.created_at as question_created_at,
    q.updated_at as question_updated_at
FROM sections s
LEFT JOIN questions q ON s.id = q.section_id
WHERE s.form_id = $1
ORDER BY
    s.id ASC,
    q."order" ASC
`

type ListByFormIDRow struct {
	SectionID           uuid.UUID
	FormID              uuid.UUID
	Title               pgtype.Text
	Progress            SectionProgress
	Description         pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ID                  pgtype.UUID
	Required            pgtype.Bool
	Type                NullQuestionType
	QuestionTitle       pgtype.Text
	QuestionDescription pgtype.Text
	Metadata            []byte
	Order               pgtype.Int4
	SourceID            pgtype.UUID
	QuestionCreatedAt   pgtype.Timestamptz
	QuestionUpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListByFormID(ctx context.Context, formID uuid.UUID) ([]ListByFormIDRow, error) {
	rows, err := q.db.Query(ctx, listByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByFormIDRow
	for rows.Next() {
		var i ListByFormIDRow
		if err := rows.Scan(
			&i.SectionID,
			&i.FormID,
			&i.Title,
			&i.Progress,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
			&i.Required,
			&i.Type,
			&i.QuestionTitle,
			&i.QuestionDescription,
			&i.Metadata,
			&i.Order,
			&i.SourceID,
			&i.QuestionCreatedAt,
			&i.QuestionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
WITH updated AS (
    UPDATE questions
    SET required = $3, type = $4, title = $5, description = $6, metadata = $7, source_id = $8, updated_at = now()
    WHERE questions.section_id = $1 AND questions.id = $2
    RETURNING id, section_id, required, type, title, description, metadata, "order", source_id, created_at, updated_at
)
SELECT 
    u.id,
    u.section_id,
    u.required,
    u.type,
    u.title,
    u.description,
    u.metadata,
    u."order",
    u.source_id,
    u.created_at,
    u.updated_at,
    s.form_id
FROM updated u
JOIN sections s ON u.section_id = s.id
`

type UpdateParams struct {
	SectionID   uuid.UUID
	ID          uuid.UUID
	Required    bool
	Type        QuestionType
	Title       pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	SourceID    pgtype.UUID
}

type UpdateRow struct {
	ID          uuid.UUID
	SectionID   uuid.UUID
	Required    bool
	Type        QuestionType
	Title       pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	Order       int32
	SourceID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	FormID      uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (UpdateRow, error) {
	row := q.db.QueryRow(ctx, update,
		arg.SectionID,
		arg.ID,
		arg.Required,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Metadata,
		arg.SourceID,
	)
	var i UpdateRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormID,
	)
	return i, err
}

const updateOrder = `-- name: UpdateOrder :one
WITH shifted AS (
    UPDATE questions
    SET "order" = CASE
        -- Moving down: shift questions between old and new position up
        WHEN $3 > (SELECT q2."order" FROM questions q2 WHERE q2.id = $2 AND q2.section_id = $1) 
             AND questions."order" > (SELECT q2."order" FROM questions q2 WHERE q2.id = $2 AND q2.section_id = $1) 
             AND questions."order" <= $3
        THEN questions."order" - 1
        -- Moving up: shift questions between new and old position down
        WHEN $3 < (SELECT q2."order" FROM questions q2 WHERE q2.id = $2 AND q2.section_id = $1)
             AND questions."order" >= $3
             AND questions."order" < (SELECT q2."order" FROM questions q2 WHERE q2.id = $2 AND q2.section_id = $1)
        THEN questions."order" + 1
        ELSE questions."order"
    END,
    updated_at = now()
    WHERE questions.section_id = $1 AND questions.id != $2
    RETURNING questions.id
),
updated AS (
    UPDATE questions q
    SET "order" = $3, updated_at = now()
    WHERE q.id = $2 AND q.section_id = $1
    RETURNING q.id, q.section_id, q.required, q.type, q.title, q.description, q.metadata, q."order", q.source_id, q.created_at, q.updated_at
)
SELECT 
    u.id,
    u.section_id,
    u.required,
    u.type,
    u.title,
    u.description,
    u.metadata,
    u."order",
    u.source_id,
    u.created_at,
    u.updated_at,
    s.form_id
FROM updated u
JOIN sections s ON u.section_id = s.id
`

type UpdateOrderParams struct {
	SectionID uuid.UUID
	ID        uuid.UUID
	Order     int32
}

type UpdateOrderRow struct {
	ID          uuid.UUID
	SectionID   uuid.UUID
	Required    bool
	Type        QuestionType
	Title       pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	Order       int32
	SourceID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	FormID      uuid.UUID
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (UpdateOrderRow, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.SectionID, arg.ID, arg.Order)
	var i UpdateOrderRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormID,
	)
	return i, err
}
