// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package question

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO questions (section_id, required, type, title, description, metadata, "order", source_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, section_id, required, type, title, description, metadata, "order", source_id, created_at, updated_at
`

type CreateParams struct {
	SectionID   uuid.UUID
	Required    bool
	Type        QuestionType
	Title       pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	Order       int32
	SourceID    pgtype.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Question, error) {
	row := q.db.QueryRow(ctx, create,
		arg.SectionID,
		arg.Required,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Metadata,
		arg.Order,
		arg.SourceID,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM questions WHERE section_id = $1 AND id = $2
`

type DeleteParams struct {
	SectionID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) error {
	_, err := q.db.Exec(ctx, delete, arg.SectionID, arg.ID)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, section_id, required, type, title, description, metadata, "order", source_id, created_at, updated_at FROM questions WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listByFormID = `-- name: ListByFormID :many
SELECT
    s.id as section_id,
    s.form_id,
    s.title,
    s.progress,
    s.description,
    s.created_at,
    s.updated_at,
    q.id,
    q.required,
    q.type,
    q.title as question_title,
    q.description as question_description,
    q.metadata,
    q."order",
    q.source_id,
    q.created_at as question_created_at,
    q.updated_at as question_updated_at
FROM sections s
LEFT JOIN questions q ON s.id = q.section_id
WHERE s.form_id = $1
ORDER BY
    s.id ASC,
    q."order" ASC
`

type ListByFormIDRow struct {
	SectionID           uuid.UUID
	FormID              uuid.UUID
	Title               pgtype.Text
	Progress            SectionProgress
	Description         pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ID                  pgtype.UUID
	Required            pgtype.Bool
	Type                NullQuestionType
	QuestionTitle       pgtype.Text
	QuestionDescription pgtype.Text
	Metadata            []byte
	Order               pgtype.Int4
	SourceID            pgtype.UUID
	QuestionCreatedAt   pgtype.Timestamptz
	QuestionUpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListByFormID(ctx context.Context, formID uuid.UUID) ([]ListByFormIDRow, error) {
	rows, err := q.db.Query(ctx, listByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByFormIDRow
	for rows.Next() {
		var i ListByFormIDRow
		if err := rows.Scan(
			&i.SectionID,
			&i.FormID,
			&i.Title,
			&i.Progress,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
			&i.Required,
			&i.Type,
			&i.QuestionTitle,
			&i.QuestionDescription,
			&i.Metadata,
			&i.Order,
			&i.SourceID,
			&i.QuestionCreatedAt,
			&i.QuestionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE questions
SET required = $3, type = $4, title = $5, description = $6, metadata = $7, "order" = $8, source_id = $8, updated_at = now()
WHERE section_id = $1 AND id = $2
    RETURNING id, section_id, required, type, title, description, metadata, "order", source_id, created_at, updated_at
`

type UpdateParams struct {
	SectionID   uuid.UUID
	ID          uuid.UUID
	Required    bool
	Type        QuestionType
	Title       pgtype.Text
	Description pgtype.Text
	Metadata    []byte
	Order       int32
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Question, error) {
	row := q.db.QueryRow(ctx, update,
		arg.SectionID,
		arg.ID,
		arg.Required,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Metadata,
		arg.Order,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Required,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.Order,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
