// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package auth

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthProvider struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Provider     string
	ClientID     string
	ClientSecret string
	RedirectUri  string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Name      string
	Username  string
	AvatarUrl string
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
