// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package user

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AnswerType string

const (
	AnswerTypeShortText      AnswerType = "short_text"
	AnswerTypeLongText       AnswerType = "long_text"
	AnswerTypeSingleChoice   AnswerType = "single_choice"
	AnswerTypeMultipleChoice AnswerType = "multiple_choice"
	AnswerTypeDate           AnswerType = "date"
)

func (e *AnswerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnswerType(s)
	case string:
		*e = AnswerType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnswerType: %T", src)
	}
	return nil
}

type NullAnswerType struct {
	AnswerType AnswerType
	Valid      bool // Valid is true if AnswerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnswerType) Scan(value interface{}) error {
	if value == nil {
		ns.AnswerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnswerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnswerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnswerType), nil
}

type Answer struct {
	ID         uuid.UUID
	ResponseID uuid.UUID
	QuestionID uuid.UUID
	Type       AnswerType
	Value      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Auth struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Provider   string
	ProviderID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type RefreshToken struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	IsActive       pgtype.Bool
	ExpirationDate pgtype.Timestamptz
}

type Response struct {
	ID          uuid.UUID
	FormID      uuid.UUID
	SubmittedBy uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Name      pgtype.Text
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	Role      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
