// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package unit

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO unit_members (unit_id, member_id)
VALUES ($1, $2)
RETURNING unit_id, member_id
`

type AddMemberParams struct {
	UnitID   uuid.UUID
	MemberID uuid.UUID
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (UnitMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.UnitID, arg.MemberID)
	var i UnitMember
	err := row.Scan(&i.UnitID, &i.MemberID)
	return i, err
}

const addParentChild = `-- name: AddParentChild :one
INSERT INTO parent_child (parent_id, child_id, org_id)
VALUES ($1, $2, $3)
RETURNING parent_id, child_id, org_id
`

type AddParentChildParams struct {
	ParentID pgtype.UUID
	ChildID  uuid.UUID
	OrgID    uuid.UUID
}

func (q *Queries) AddParentChild(ctx context.Context, arg AddParentChildParams) (ParentChild, error) {
	row := q.db.QueryRow(ctx, addParentChild, arg.ParentID, arg.ChildID, arg.OrgID)
	var i ParentChild
	err := row.Scan(&i.ParentID, &i.ChildID, &i.OrgID)
	return i, err
}

const create = `-- name: Create :one
INSERT INTO units (name, org_id, description, metadata, type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, type, name, description, metadata, created_at, updated_at
`

type CreateParams struct {
	Name        pgtype.Text
	OrgID       pgtype.UUID
	Description pgtype.Text
	Metadata    []byte
	Type        UnitType
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Unit, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.OrgID,
		arg.Description,
		arg.Metadata,
		arg.Type,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM units WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const getAllOrganizations = `-- name: GetAllOrganizations :many
SELECT id, org_id, type, name, description, metadata, created_at, updated_at FROM units WHERE type = 'organization'
`

func (q *Queries) GetAllOrganizations(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, getAllOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, org_id, type, name, description, metadata, created_at, updated_at FROM units WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT member_id FROM unit_members WHERE unit_id = $1
`

func (q *Queries) ListMembers(ctx context.Context, unitID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMembers, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var member_id uuid.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubUnitIDs = `-- name: ListSubUnitIDs :many
SELECT child_id FROM parent_child WHERE parent_id = $1
`

func (q *Queries) ListSubUnitIDs(ctx context.Context, parentID pgtype.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSubUnitIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var child_id uuid.UUID
		if err := rows.Scan(&child_id); err != nil {
			return nil, err
		}
		items = append(items, child_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubUnits = `-- name: ListSubUnits :many
SELECT u.id, u.org_id, u.type, u.name, u.description, u.metadata, u.created_at, u.updated_at FROM units u
JOIN parent_child pc ON u.id = pc.child_id
WHERE pc.parent_id = $1
`

func (q *Queries) ListSubUnits(ctx context.Context, parentID pgtype.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listSubUnits, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsMembers = `-- name: ListUnitsMembers :many
SELECT unit_id, member_id
FROM unit_members
WHERE unit_id = ANY($1::uuid[])
`

func (q *Queries) ListUnitsMembers(ctx context.Context, dollar_1 []uuid.UUID) ([]UnitMember, error) {
	rows, err := q.db.Query(ctx, listUnitsMembers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitMember
	for rows.Next() {
		var i UnitMember
		if err := rows.Scan(&i.UnitID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParentChild = `-- name: RemoveParentChild :exec
DELETE FROM parent_child WHERE child_id = $1
`

func (q *Queries) RemoveParentChild(ctx context.Context, childID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeParentChild, childID)
	return err
}

const update = `-- name: Update :one
UPDATE units
SET name = $2, description = $3, metadata = $4, updated_at = now()
WHERE id = $1
RETURNING id, org_id, type, name, description, metadata, created_at, updated_at
`

type UpdateParams struct {
	ID          uuid.UUID
	Name        pgtype.Text
	Description pgtype.Text
	Metadata    []byte
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Unit, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Metadata,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
